<?php
/**
 * Rate
 *
 * PHP version 5
 *
 * @category Class
 * @package  PurplShip
 * @author   PurplShip Codegen team
 * @link     https://github.com/purplship/purplship-clients
 */

/**
 * PurplShip Multi-carrier API
 *
 * PurplShip is a Multi-carrier Shipping API that simplifies the integration of logistic carrier services
 *
 * OpenAPI spec version: v1
 * Contact: hello@purplship.com
 * Generated by: https://github.com/purplship/purplship-clients.git
 * PurplShip Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/purplship/purplship-clients
 * Do not edit the class manually.
 */

namespace PurplShip\Model;

use \ArrayAccess;
use \PurplShip\ObjectSerializer;

/**
 * Rate Class Doc Comment
 *
 * @category Class
 * @package  PurplShip
 * @author   PurplShip Codegen team
 * @link     https://github.com/purplship/purplship-clients
 */
class Rate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Rate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'carrier_name' => 'string',
        'carrier_id' => 'string',
        'currency' => 'string',
        'service' => 'string',
        'discount' => 'float',
        'base_charge' => 'float',
        'total_charge' => 'float',
        'duties_and_taxes' => 'float',
        'estimated_delivery' => 'string',
        'extra_charges' => '\PurplShip\Model\Charge[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'uuid',
        'carrier_name' => null,
        'carrier_id' => null,
        'currency' => null,
        'service' => null,
        'discount' => null,
        'base_charge' => null,
        'total_charge' => null,
        'duties_and_taxes' => null,
        'estimated_delivery' => null,
        'extra_charges' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'carrier_name' => 'carrierName',
        'carrier_id' => 'carrierId',
        'currency' => 'currency',
        'service' => 'service',
        'discount' => 'discount',
        'base_charge' => 'baseCharge',
        'total_charge' => 'totalCharge',
        'duties_and_taxes' => 'dutiesAndTaxes',
        'estimated_delivery' => 'estimatedDelivery',
        'extra_charges' => 'extraCharges'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'carrier_name' => 'setCarrierName',
        'carrier_id' => 'setCarrierId',
        'currency' => 'setCurrency',
        'service' => 'setService',
        'discount' => 'setDiscount',
        'base_charge' => 'setBaseCharge',
        'total_charge' => 'setTotalCharge',
        'duties_and_taxes' => 'setDutiesAndTaxes',
        'estimated_delivery' => 'setEstimatedDelivery',
        'extra_charges' => 'setExtraCharges'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'carrier_name' => 'getCarrierName',
        'carrier_id' => 'getCarrierId',
        'currency' => 'getCurrency',
        'service' => 'getService',
        'discount' => 'getDiscount',
        'base_charge' => 'getBaseCharge',
        'total_charge' => 'getTotalCharge',
        'duties_and_taxes' => 'getDutiesAndTaxes',
        'estimated_delivery' => 'getEstimatedDelivery',
        'extra_charges' => 'getExtraCharges'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['carrier_name'] = isset($data['carrier_name']) ? $data['carrier_name'] : null;
        $this->container['carrier_id'] = isset($data['carrier_id']) ? $data['carrier_id'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['service'] = isset($data['service']) ? $data['service'] : null;
        $this->container['discount'] = isset($data['discount']) ? $data['discount'] : null;
        $this->container['base_charge'] = isset($data['base_charge']) ? $data['base_charge'] : null;
        $this->container['total_charge'] = isset($data['total_charge']) ? $data['total_charge'] : null;
        $this->container['duties_and_taxes'] = isset($data['duties_and_taxes']) ? $data['duties_and_taxes'] : null;
        $this->container['estimated_delivery'] = isset($data['estimated_delivery']) ? $data['estimated_delivery'] : null;
        $this->container['extra_charges'] = isset($data['extra_charges']) ? $data['extra_charges'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['carrier_name'] === null) {
            $invalidProperties[] = "'carrier_name' can't be null";
        }
        if ((mb_strlen($this->container['carrier_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'carrier_name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['carrier_id'] === null) {
            $invalidProperties[] = "'carrier_id' can't be null";
        }
        if ((mb_strlen($this->container['carrier_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'carrier_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ((mb_strlen($this->container['currency']) < 1)) {
            $invalidProperties[] = "invalid value for 'currency', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['service']) && (mb_strlen($this->container['service']) < 1)) {
            $invalidProperties[] = "invalid value for 'service', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['estimated_delivery']) && (mb_strlen($this->container['estimated_delivery']) < 1)) {
            $invalidProperties[] = "invalid value for 'estimated_delivery', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id A unique rate identifier
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets carrier_name
     *
     * @return string
     */
    public function getCarrierName()
    {
        return $this->container['carrier_name'];
    }

    /**
     * Sets carrier_name
     *
     * @param string $carrier_name The rate's carrier
     *
     * @return $this
     */
    public function setCarrierName($carrier_name)
    {

        if ((mb_strlen($carrier_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $carrier_name when calling Rate., must be bigger than or equal to 1.');
        }

        $this->container['carrier_name'] = $carrier_name;

        return $this;
    }

    /**
     * Gets carrier_id
     *
     * @return string
     */
    public function getCarrierId()
    {
        return $this->container['carrier_id'];
    }

    /**
     * Sets carrier_id
     *
     * @param string $carrier_id The targeted carrier's name (unique identifier)
     *
     * @return $this
     */
    public function setCarrierId($carrier_id)
    {

        if ((mb_strlen($carrier_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $carrier_id when calling Rate., must be bigger than or equal to 1.');
        }

        $this->container['carrier_id'] = $carrier_id;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency The rate monetary values currency code
     *
     * @return $this
     */
    public function setCurrency($currency)
    {

        if ((mb_strlen($currency) < 1)) {
            throw new \InvalidArgumentException('invalid length for $currency when calling Rate., must be bigger than or equal to 1.');
        }

        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets service
     *
     * @return string
     */
    public function getService()
    {
        return $this->container['service'];
    }

    /**
     * Sets service
     *
     * @param string $service The carrier's rate (quote) service
     *
     * @return $this
     */
    public function setService($service)
    {

        if (!is_null($service) && (mb_strlen($service) < 1)) {
            throw new \InvalidArgumentException('invalid length for $service when calling Rate., must be bigger than or equal to 1.');
        }

        $this->container['service'] = $service;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return float
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param float $discount The monetary amount of the discount on the rate
     *
     * @return $this
     */
    public function setDiscount($discount)
    {
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets base_charge
     *
     * @return float
     */
    public function getBaseCharge()
    {
        return $this->container['base_charge'];
    }

    /**
     * Sets base_charge
     *
     * @param float $base_charge The rate's monetary amount of the base charge.<br/> This is the net amount of the rate before additional charges
     *
     * @return $this
     */
    public function setBaseCharge($base_charge)
    {
        $this->container['base_charge'] = $base_charge;

        return $this;
    }

    /**
     * Gets total_charge
     *
     * @return float
     */
    public function getTotalCharge()
    {
        return $this->container['total_charge'];
    }

    /**
     * Sets total_charge
     *
     * @param float $total_charge The rate's monetary amount of the total charge.<br/> This is the gross amount of the rate after adding the additional charges
     *
     * @return $this
     */
    public function setTotalCharge($total_charge)
    {
        $this->container['total_charge'] = $total_charge;

        return $this;
    }

    /**
     * Gets duties_and_taxes
     *
     * @return float
     */
    public function getDutiesAndTaxes()
    {
        return $this->container['duties_and_taxes'];
    }

    /**
     * Sets duties_and_taxes
     *
     * @param float $duties_and_taxes The monetary amount of the duties and taxes if applied
     *
     * @return $this
     */
    public function setDutiesAndTaxes($duties_and_taxes)
    {
        $this->container['duties_and_taxes'] = $duties_and_taxes;

        return $this;
    }

    /**
     * Gets estimated_delivery
     *
     * @return string
     */
    public function getEstimatedDelivery()
    {
        return $this->container['estimated_delivery'];
    }

    /**
     * Sets estimated_delivery
     *
     * @param string $estimated_delivery The estimated delivery date
     *
     * @return $this
     */
    public function setEstimatedDelivery($estimated_delivery)
    {

        if (!is_null($estimated_delivery) && (mb_strlen($estimated_delivery) < 1)) {
            throw new \InvalidArgumentException('invalid length for $estimated_delivery when calling Rate., must be bigger than or equal to 1.');
        }

        $this->container['estimated_delivery'] = $estimated_delivery;

        return $this;
    }

    /**
     * Gets extra_charges
     *
     * @return \PurplShip\Model\Charge[]
     */
    public function getExtraCharges()
    {
        return $this->container['extra_charges'];
    }

    /**
     * Sets extra_charges
     *
     * @param \PurplShip\Model\Charge[] $extra_charges list of the rate's additional charges
     *
     * @return $this
     */
    public function setExtraCharges($extra_charges)
    {
        $this->container['extra_charges'] = $extra_charges;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


