<?php
/**
 * Webhook
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Karrio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Karrio API
 *
 * ## API Reference  Karrio is an open source multi-carrier shipping API that simplifies the integration of logistic carrier services.  The Karrio API is organized around REST. Our API has predictable resource-oriented URLs, accepts JSON-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.  The Karrio API differs for every account as we release new versions. These docs are customized to your version of the API.   ## Versioning  When backwards-incompatible changes are made to the API, a new, dated version is released. The current version is `2022.4`.  Read our API changelog and to learn more about backwards compatibility.  As a precaution, use API versioning to check a new API version before committing to an upgrade.   ## Pagination  All top-level API resources have support for bulk fetches via \"list\" API methods. For instance, you can list addresses, list shipments, and list trackers. These list API methods share a common structure, taking at least these two parameters: limit, and offset.  Karrio utilizes offset-based pagination via the offset and limit parameters. Both parameters take a number as value (see below) and return objects in reverse chronological order. The offset parameter returns objects listed after an index. The limit parameter take a limit on the number of objects to be returned from 1 to 100.   ```json {     \"next\": \"/v1/shipments?limit=25&offset=25\",     \"previous\": \"/v1/shipments?limit=25&offset=25\",     \"results\": [     ] } ```  ## Environments  The Karrio API offer the possibility to create and retrieve certain objects in `test_mode`. In development, it is therefore possible to add carrier connections, get live rates, buy labels, create trackers and schedule pickups in `test_mode`.
 *
 * The version of the OpenAPI document: 2022.4
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Karrio\Model;

use \ArrayAccess;
use \Karrio\ObjectSerializer;

/**
 * Webhook Class Doc Comment
 *
 * @category Class
 * @package  Karrio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Webhook implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Webhook';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'url' => 'string',
        'description' => 'string',
        'enabled_events' => 'string[]',
        'test_mode' => 'bool',
        'disabled' => 'bool',
        'object_type' => 'string',
        'last_event_at' => '\DateTime',
        'secret' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'url' => 'uri',
        'description' => null,
        'enabled_events' => null,
        'test_mode' => null,
        'disabled' => null,
        'object_type' => null,
        'last_event_at' => 'date-time',
        'secret' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'url' => 'url',
        'description' => 'description',
        'enabled_events' => 'enabled_events',
        'test_mode' => 'test_mode',
        'disabled' => 'disabled',
        'object_type' => 'object_type',
        'last_event_at' => 'last_event_at',
        'secret' => 'secret'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'url' => 'setUrl',
        'description' => 'setDescription',
        'enabled_events' => 'setEnabledEvents',
        'test_mode' => 'setTestMode',
        'disabled' => 'setDisabled',
        'object_type' => 'setObjectType',
        'last_event_at' => 'setLastEventAt',
        'secret' => 'setSecret'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'url' => 'getUrl',
        'description' => 'getDescription',
        'enabled_events' => 'getEnabledEvents',
        'test_mode' => 'getTestMode',
        'disabled' => 'getDisabled',
        'object_type' => 'getObjectType',
        'last_event_at' => 'getLastEventAt',
        'secret' => 'getSecret'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const ENABLED_EVENTS_ALL = 'all';
    const ENABLED_EVENTS_SHIPMENT_PURCHASED = 'shipment.purchased';
    const ENABLED_EVENTS_SHIPMENT_CANCELLED = 'shipment.cancelled';
    const ENABLED_EVENTS_SHIPMENT_FULFILLED = 'shipment.fulfilled';
    const ENABLED_EVENTS_TRACKER_CREATED = 'tracker.created';
    const ENABLED_EVENTS_TRACKER_UPDATED = 'tracker.updated';
    const ENABLED_EVENTS_ORDER_CREATED = 'order.created';
    const ENABLED_EVENTS_ORDER_FULFILLED = 'order.fulfilled';
    const ENABLED_EVENTS_ORDER_CANCELLED = 'order.cancelled';
    const ENABLED_EVENTS_ORDER_DELIVERED = 'order.delivered';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnabledEventsAllowableValues()
    {
        return [
            self::ENABLED_EVENTS_ALL,
            self::ENABLED_EVENTS_SHIPMENT_PURCHASED,
            self::ENABLED_EVENTS_SHIPMENT_CANCELLED,
            self::ENABLED_EVENTS_SHIPMENT_FULFILLED,
            self::ENABLED_EVENTS_TRACKER_CREATED,
            self::ENABLED_EVENTS_TRACKER_UPDATED,
            self::ENABLED_EVENTS_ORDER_CREATED,
            self::ENABLED_EVENTS_ORDER_FULFILLED,
            self::ENABLED_EVENTS_ORDER_CANCELLED,
            self::ENABLED_EVENTS_ORDER_DELIVERED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['url'] = $data['url'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['enabled_events'] = $data['enabled_events'] ?? null;
        $this->container['test_mode'] = $data['test_mode'] ?? null;
        $this->container['disabled'] = $data['disabled'] ?? null;
        $this->container['object_type'] = $data['object_type'] ?? 'webhook';
        $this->container['last_event_at'] = $data['last_event_at'] ?? null;
        $this->container['secret'] = $data['secret'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && (mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ((mb_strlen($this->container['url']) < 1)) {
            $invalidProperties[] = "invalid value for 'url', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['enabled_events'] === null) {
            $invalidProperties[] = "'enabled_events' can't be null";
        }
        if ($this->container['test_mode'] === null) {
            $invalidProperties[] = "'test_mode' can't be null";
        }
        if (!is_null($this->container['object_type']) && (mb_strlen($this->container['object_type']) < 1)) {
            $invalidProperties[] = "invalid value for 'object_type', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['secret'] === null) {
            $invalidProperties[] = "'secret' can't be null";
        }
        if ((mb_strlen($this->container['secret']) < 1)) {
            $invalidProperties[] = "invalid value for 'secret', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id A unique identifier
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && (mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling Webhook., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The URL of the webhook endpoint.
     *
     * @return self
     */
    public function setUrl($url)
    {

        if ((mb_strlen($url) < 1)) {
            throw new \InvalidArgumentException('invalid length for $url when calling Webhook., must be bigger than or equal to 1.');
        }

        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description An optional description of what the webhook is used for.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets enabled_events
     *
     * @return string[]
     */
    public function getEnabledEvents()
    {
        return $this->container['enabled_events'];
    }

    /**
     * Sets enabled_events
     *
     * @param string[] $enabled_events The list of events to enable for this endpoint.
     *
     * @return self
     */
    public function setEnabledEvents($enabled_events)
    {
        $allowedValues = $this->getEnabledEventsAllowableValues();
        if (array_diff($enabled_events, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'enabled_events', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['enabled_events'] = $enabled_events;

        return $this;
    }

    /**
     * Gets test_mode
     *
     * @return bool
     */
    public function getTestMode()
    {
        return $this->container['test_mode'];
    }

    /**
     * Sets test_mode
     *
     * @param bool $test_mode Specified whether it was created with a carrier in test mode
     *
     * @return self
     */
    public function setTestMode($test_mode)
    {
        $this->container['test_mode'] = $test_mode;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool|null
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool|null $disabled Indicates that the webhook is disabled
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        $this->container['disabled'] = $disabled;

        return $this;
    }

    /**
     * Gets object_type
     *
     * @return string|null
     */
    public function getObjectType()
    {
        return $this->container['object_type'];
    }

    /**
     * Sets object_type
     *
     * @param string|null $object_type Specifies the object type
     *
     * @return self
     */
    public function setObjectType($object_type)
    {

        if (!is_null($object_type) && (mb_strlen($object_type) < 1)) {
            throw new \InvalidArgumentException('invalid length for $object_type when calling Webhook., must be bigger than or equal to 1.');
        }

        $this->container['object_type'] = $object_type;

        return $this;
    }

    /**
     * Gets last_event_at
     *
     * @return \DateTime|null
     */
    public function getLastEventAt()
    {
        return $this->container['last_event_at'];
    }

    /**
     * Sets last_event_at
     *
     * @param \DateTime|null $last_event_at The datetime of the last event sent.
     *
     * @return self
     */
    public function setLastEventAt($last_event_at)
    {
        $this->container['last_event_at'] = $last_event_at;

        return $this;
    }

    /**
     * Gets secret
     *
     * @return string
     */
    public function getSecret()
    {
        return $this->container['secret'];
    }

    /**
     * Sets secret
     *
     * @param string $secret Header signature secret
     *
     * @return self
     */
    public function setSecret($secret)
    {

        if ((mb_strlen($secret) < 1)) {
            throw new \InvalidArgumentException('invalid length for $secret when calling Webhook., must be bigger than or equal to 1.');
        }

        $this->container['secret'] = $secret;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


