<?php
/**
 * PaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PurplShip
 * @author   PurplShip Codegen team
 * @link     https://github.com/purplship/purplship-clients
 */

/**
 * PurplShip Multi-carrier API
 *
 * PurplShip is a Multi-carrier Shipping API that simplifies the integration of logistic carrier services
 *
 * OpenAPI spec version: v1
 * Contact: hello@purplship.com
 * Generated by: https://github.com/purplship/purplship-clients.git
 * PurplShip Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/purplship/purplship-clients
 * Please update the test case below to test the model.
 */

namespace PurplShip;

/**
 * PaymentTest Class Doc Comment
 *
 * @category    Class
 * @description The payment details
 * @package     PurplShip
 * @author      PurplShip Codegen team
 * @link        https://github.com/purplship/purplship-clients
 */
class PaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Payment"
     */
    public function testPayment()
    {
    }

    /**
     * Test attribute "paid_by"
     */
    public function testPropertyPaidBy()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {
    }

    /**
     * Test attribute "credit_card"
     */
    public function testPropertyCreditCard()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }
}
